const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const C = require('../converter.js');
const root = path.resolve(__dirname, '..');

async function main() {
  const context = {};
  vm.runInNewContext(fs.readFileSync(path.join(root, 'template.js'), 'utf8') + '\nglobalThis.template = DEFAULT_TEMPLATE_BASE64;', context);
  const entries = await C.unzip(new Uint8Array(Buffer.from(context.template, 'base64')));
  const info = C.templateInfo(entries);
  assert.equal(info.resolve('Title'), 'Title');
  assert.equal(info.resolve('ListBullet'), 'ListBullet');
  assert.equal(info.width, 9354);
  assert.ok(!info.document.includes('headerReference'));
  assert.equal(C.mdToTxt('# 标题\n\n- **甲**\n- 乙\n\n| 项目 | 内容 |\n| --- | --- |\n| 中 | 文 |'), '标题\n\n• 甲\n\n• 乙\n\n项目｜内容\n中｜文\n');
  assert.deepEqual(Array.from(C.txtBytes('中文').slice(0, 3)), [0xef, 0xbb, 0xbf]);
  assert.ok(new TextDecoder().decode(C.txtBytes('甲\n乙')).includes('\r\n'));
  assert.deepEqual(C.parse('# 标题\n副标题\n姓名').map(x => x.type), ['title', 'subtitle', 'name']);
  assert.deepEqual(C.parse('# 标题\n正文\n第二段', 'general').map(x => x.type), ['title', 'paragraph', 'paragraph']);
  assert.equal(C.parse('# 标题\n## 章节\n- 内容')[1].type, 'heading');
  assert.deepEqual(C.parse('| --- | --- |'), []);
  assert.deepEqual(C.parse('| a | b |\n| x |')[0].rows[1], ['x', '']);
  assert.equal(C.safeName('CON.md'), '_CON');
  assert.equal(C.safeName('a/b.md'), 'a_b');
  assert.equal(C.safeName(''), '未命名文档');
  const md = '# 转换测试\n副标题\n姓名\n\n<&> **重点** 😀\n\n## 章节\n- **要点**\n\n| 项目 | 设定 |\n| --- | --- |\n| 身份 | **作者** |';
  const document = C.makeDocx(md, entries);
  const result = new Map(await C.unzip(document));
  const xml = new TextDecoder().decode(result.get('word/document.xml'));
  assert.ok(xml.includes('&lt;&amp;&gt;'));
  assert.ok(xml.includes('😀'));
  assert.ok(xml.includes('<w:b/>'));
  assert.ok(xml.includes('w:styleId') === false);
  assert.ok(xml.includes('<w:pStyle w:val="ListBullet"/>'));
  assert.ok(xml.includes('<w:tblGrid>'));
  assert.ok(xml.includes('w:fill="E8EDF0"'));
  assert.equal(result.size, entries.length);
  assert.deepEqual(result.get('word/styles.xml'), new Map(entries).get('word/styles.xml'));
  const roundtrip = await C.unzip(C.zip([['中文.txt', C.txtBytes('甲')], ['sample.docx', document]]));
  assert.equal(roundtrip[0][0], '中文.txt');
  assert.deepEqual(roundtrip[1][1], document);
  const corrupted = document.slice(); corrupted[60] ^= 0xff;
  await assert.rejects(() => C.unzip(corrupted));
  await assert.rejects(() => C.unzip(new Uint8Array([1, 2, 3])));
  const qa = path.join(root, 'qa'); fs.mkdirSync(qa, { recursive: true });
  fs.writeFileSync(path.join(qa, 'generated.docx'), document);
  console.log('PASS: TXT compatibility, card/general layouts, tables, names, Unicode ZIP, DOCX, XML escaping and corrupt inputs');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
